# -*- coding: utf-8 -*-
"""Face_Detect.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VXk_VzcZX0Nok-WX19j8Gl93BwXDzfKy

#1. Import
"""

from google.colab import drive
drive.mount('/content/drive')

"""> 아래 줄을 실행하기전에 메뉴에서 런타임-런타임유형변경-하드웨어 가속기(GPU) 저장 설정이 필요"""

!pip3 install face_recognition

"""#2. Face Detection"""

# Commented out IPython magic to ensure Python compatibility.
import cv2, os
import face_recognition as fr
from IPython.display import Image, display
import matplotlib.pyplot as plt
# %matplotlib inline

"""##2.1 Image Processing"""

import glob
from PIL import Image

"""> file_path에 얼굴 추출할 대상 이미지들의 경로를 저장"""

def face_extract(file_path):
  
  files = glob.glob(file_path+"*.*")
  image = []
  for image_path in files:
    image.append(fr.load_image_file(image_path))
    # plt.imshow(image[-1])
    # plt.show()

  engineering = []

  for dst in image:
    face_locations = fr.face_locations(dst)

    face_landmarks = fr.face_landmarks(dst)

    color = (255,0,0)

    for face_location in face_locations:
      top,right,bottom,left = face_location
      cv2.rectangle(dst, (left,top),(right,bottom),color,2)
      temp_img = dst[:]
      face_img = temp_img[top:bottom,left:right]
      engineering.append(face_img)

    plt.rcParams['figure.figsize'] = (5,5)
    # plt.imshow(dst)
    # plt.show()

    plt.rcParams['figure.figsize'] = (1,1)

  
  for idx, person in enumerate(engineering):
    try:
      if not os.path.exists(file_path+'captured_images/'):
        os.mkdir(file_path+'captured_images/')
        Image.fromarray(person).save(file_path+'captured_images/face'+str(idx)+'.jpg')
      else:
        Image.fromarray(person).save(file_path+'captured_images/face'+str(idx)+'.jpg')
    except OSError:
      print(OSError)
    # plt.imshow(person)
    # plt.show()

"""> 결론적으로 인물 이미지가 있는 폴더의 경로를 매개변수로 입력하면 해당 폴더에서 captured_images 폴더를 생성하고 face0,face1.... face(n) 의 이름으로 이미지에서 얼굴을 추출하여 저장"""

file_path = '/content/drive/MyDrive/Colab Notebooks/얼굴인식프로젝트/images/'

face_extract(file_path)

